### ISSUE TITLE
RESupermethod: Incomplete parameter list

### ISSUE THREAD

**Issue by ppm** [zuccoi/REKit#11]
Currently ( e07ccd9acf0c16c2748243452707f2866b625941 ), definition of RESupermethod is:
`#define RESupermethod(defaultValue, receiver, ...)`

But it needs to be:
`#define RESupermethod(defaultValue, re_receiver, re_selector, re_isClassMethod, re_key, ...)`
doesn't it?

**Comment by zuccoi** [comment]
RESupermethod is intended to be used in Block you passed to RESetBlock.  RESetBlock declares re_receiver, etc.  You don’t need to care about them.

Arguments of RESupermethod are
-defaultValue
-receiver
-arguments of method (if needed)

Please check usage of RESupermethod written in tests.

**Comment by ppm** [comment]
Understood RESetBlock is convenience macro for `-setBlockFor…`, and within its block, I can call supermethod easier with RESupermethod macro. Thanks!

**Comment by zuccoi** [comment]
I'll add comments describing that. Thanks.
