### ISSUE TITLE
クラスメソッドの置換について

### ISSUE THREAD

**Issue by yamaya** [zuccoi/REKit#2]
クラスメソッドの置換は可能でしょうか？
可能であれば、どのようにすればよいでしょうか？

**Comment by zuccoi** [comment]
ご質問ありがとうございます。 
現在、REResponder はクラスメソッドの置換には対応していません。ただ、クラスメソッドにも対応してほしいという声はちらほらと上がっているので、今後の対応を検討しています。
もし宜しければ、どういった状況でクラスメソッドの置換をしたくなったか、教えて頂けますでしょうか。

**Comment by yamaya** [comment]
ユニットテストにおいて、主にスタブで使用したいなと思います。
Foundationを始め標準のクラスのメソッドもスタブしたいですし、自作のクラスでもクラスメソッドスタブしたくなります。

**Comment by zuccoi** [comment]
ご回答ありがとうございます。
UnitTest においてクラスメソッドをその場で(Blocks を使用して)スタブ化して、直ぐに or tearDown で元に戻したいということですよね。
クラスメソッドの対応時に参考にさせていただきます。

もしお急ぎであれば、以下のようなコードで実現可能ですのでお試しください。

``` objective-c
// Get method for [NSObject version]
Method method;
method = class_getClassMethod([NSObject class], @selector(version));

// Replace implementation of the method
IMP originalIMP;
NSInteger (^block)(id) = ^(id receiver) {
    return 1;
};
originalIMP = method_setImplementation(method, REBlockGetImplementation(block));

// Call version
NSInteger version;
version = [NSObject version];
STAssertEquals(version, 1, @"");

// Tear down
method_setImplementation(method, originalIMP);
```

**Comment by zuccoi** [comment]
解決でしたら、クローズをお願い致します。

**Comment by zuccoi** [comment]
クラスメソッドの置換に対応したブランチ feat/ClassMethod をプッシュしてみました。
https://github.com/zuccoi/REKit/tree/feat/ClassMethod
よかったら触ってみてください。
